<?php

namespace Relationships\OneToMany\UniDirectional;

use Doctrine\ORM\EntityRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository
{
    /**
     * @return Order[]
     */
    public function dqlFindAll(): array
    {
        $query = $this->getEntityManager()->createQuery('
          SELECT
            o, li
          FROM
            ' . Order::class . ' o
          JOIN o.lineItems li
        ');

        return $query->getResult();
    }
}
